Closure compiler fix for iron-menu-behavior.html
Fixes the following closure compiler error in Chromium:

## src/third_party/polymer/v1_0/components-chromium/iron-menu-behavior/iron-menu-behavior-extracted.js:229: ERROR - actual parameter 1 of PolymerElement.prototype.isLightDescendant does not match formal parameter
## found   : EventTarget
## required: (Node|null)
##       if (rootTarget !== this && typeof rootTarget.tabIndex !== "undefined" && !this.isLightDescendant(rootTarget)) {
##                                                                                                        ^